# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics_db
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports: ["6379:6379"]
    volumes: [redis_data:/data]
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq_broker
    ports: ["5672:5672", "15672:15672"]
volumes:
  postgres_data:
  redis_data: